@echo off
echo Initializing Git repository...
git init
echo Adding files...
git add .
echo Committing changes...
git commit -m "Initial push: Elite Hola9 Marketplace Frontend"
echo Setting remote origin...
git remote add origin https://github.com/Pavansai0427/hola9-mockup.git
echo Pushing to GitHub...
git branch -M main
git push -u origin main
echo Done!
pause
